export const TRIGGER_LOAD = 'EXAMPLE 1 / TRIGGER_LOAD';

export const LOADING_START = 'EXAMPLE 1 / LOADING_START';
export const LOADING_SUCCESS  = 'EXAMPLE 1 / LOADING_SUCCESS';

export const RESET = 'EXAMPLE 1 / RESET';
