export const TRIGGER_LEADING = 'EXAMPLE 3 / TRIGGER_LEADING';
export const LEADING_START = 'EXAMPLE 3 / LEADING_START';
export const LEADING_STOP = 'EXAMPLE 3 / LEADING_STOP';

export const TRIGGER_LATEST = 'EXAMPLE 3 / TRIGGER_LATEST';
export const LATEST_START = 'EXAMPLE 3 / LATEST_START';
export const LATEST_STOP = 'EXAMPLE 3 / LATEST_STOP';

export const RESET = 'EXAMPLE 3 / RESET';
